# Generated by Django 4.1.1 on 2022-09-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New App', max_length=120)),
                ('profile_picture', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New App', max_length=120)),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeMachine.user')),
            ],
            options={
                'db_table': 'rulesets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New App', max_length=120)),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('expression', models.TextField(blank=True)),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('fields', models.JSONField()),
                ('weightage', models.IntegerField(default=0)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeMachine.ruleset')),
            ],
            options={
                'db_table': 'rules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New App', max_length=125)),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('display_picture', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeMachine.user')),
            ],
            options={
                'db_table': 'apps',
                'managed': True,
            },
        ),
    ]
