# Generated by Django 4.1.1 on 2022-09-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeMachine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='payload',
            field=models.JSONField(null=True),
        ),
    ]
