# Generated by Django 4.1.1 on 2022-09-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeMachine', '0002_rules_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coffeeMachine.app'),
        ),
    ]
