# Generated by Django 4.1.1 on 2022-09-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeMachine', '0003_ruleset_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
